services:

  postgres:
    image: postgres:16.2
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cujae
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"   # host:container
    restart: unless-stopped

  backend:
    image: backend-backend:latest
    container_name: backend
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cujae
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      APP_BOOTSTRAP_ADMIN_EMAIL: ${APP_BOOTSTRAP_ADMIN_EMAIL:-}
      APP_BOOTSTRAP_ADMIN_PASSWORD: ${APP_BOOTSTRAP_ADMIN_PASSWORD:-}
      APP_BOOTSTRAP_ADMIN_NAME: ${APP_BOOTSTRAP_ADMIN_NAME:-Admin}
    ports:
      - "8080:8080"
    restart: unless-stopped

  backend-dev:
    image: maven:3.9.6-eclipse-temurin-17
    container_name: backend-dev
    working_dir: /app
    command: mvn -DskipTests spring-boot:run
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cujae
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DEVTOOLS_RESTART_ENABLED: "true"
      SPRING_DEVTOOLS_RESTART_POLL_INTERVAL: 2s
      SPRING_DEVTOOLS_RESTART_QUIET_PERIOD: 1s
      APP_BOOTSTRAP_ADMIN_EMAIL: ${APP_BOOTSTRAP_ADMIN_EMAIL:-}
      APP_BOOTSTRAP_ADMIN_PASSWORD: ${APP_BOOTSTRAP_ADMIN_PASSWORD:-}
      APP_BOOTSTRAP_ADMIN_NAME: ${APP_BOOTSTRAP_ADMIN_NAME:-Admin}
    volumes:
      - ./:/app
      - maven_cache:/root/.m2
    ports:
      - "8081:8080"
    profiles:
      - dev
    restart: unless-stopped

volumes:
  postgres_data:
  maven_cache:
